// GENERATED by scripts/gen-ad-domains.mjs — do not edit by hand.
// 141 ad-network eTLD+1s, verified against EasyList 2026-06-11.
// Plain script (no modules): loaded before detector.js/inspector.js in
// content scripts, importScripts'd by the service worker, <script>'d by the
// options page. Defines globals only.

// Detection set: an iframe whose src host has any suffix in here is an ad.
const TROVE_AD_DOMAINS = new Set([
  "1rx.io",
  "2mdn.net",
  "33across.com",
  "360yield.com",
  "3lift.com",
  "ad-srv.net",
  "adblade.com",
  "adcash.com",
  "adform.net",
  "adition.com",
  "adkernel.com",
  "adlightning.com",
  "adlooxtracking.com",
  "admedia.com",
  "admixer.md",
  "admixer.net",
  "admob.com",
  "adnxs-simple.com",
  "adnxs.com",
  "adnxs.net",
  "adroll.com",
  "adsafeprotected.com",
  "adscale.de",
  "adskeeper.co.uk",
  "adskeeper.com",
  "adsrvr.org",
  "adsterra.com",
  "adtech.de",
  "adtechus.com",
  "adtng.com",
  "adyoulike.com",
  "amazon-adsystem.com",
  "amobee.com",
  "aniview.com",
  "bidswitch.net",
  "bidvertiser.com",
  "bttrack.com",
  "casalemedia.com",
  "contextweb.com",
  "criteo.com",
  "criteo.net",
  "crwdcntrl.net",
  "dianomi.com",
  "districtm.ca",
  "districtm.io",
  "dotomi.com",
  "doubleclick.com",
  "doubleclick.net",
  "doubleverify.com",
  "emxdgt.com",
  "eskimi.com",
  "exoclick.com",
  "exosrv.com",
  "exponential.com",
  "eyeota.net",
  "flashtalking.com",
  "fwmrm.net",
  "gammaplatform.com",
  "googleadservices.com",
  "googlesyndication.com",
  "googletagservices.com",
  "gumgum.com",
  "id5-sync.com",
  "imonomy.com",
  "improvedigital.com",
  "indexww.com",
  "infolinks.com",
  "innovid.com",
  "insurads.com",
  "juicyads.com",
  "juicyads.me",
  "kargo.com",
  "kontera.com",
  "liadm.com",
  "lijit.com",
  "lkqd.net",
  "loopme.me",
  "media.net",
  "mediafuse.com",
  "mgid.com",
  "minutemedia-prebid.com",
  "moatads.com",
  "msads.net",
  "ntv.io",
  "onetag-sys.com",
  "openx.net",
  "outbrain.com",
  "outbrainimg.com",
  "plista.com",
  "popads.media",
  "popads.net",
  "popcash.net",
  "powerlinks.com",
  "pro-market.net",
  "propellerads.com",
  "propellerads.tech",
  "propellerclick.com",
  "pubmatic.com",
  "revcontent.com",
  "revenuehits.com",
  "rfihub.com",
  "rfihub.net",
  "richaudience.com",
  "rlcdn.com",
  "rubiconproject.com",
  "sascdn.com",
  "seedtag.com",
  "sekindo.com",
  "sharethrough.com",
  "smaato.net",
  "smartadserver.com",
  "smartclip.net",
  "smilewanted.com",
  "sonobi.com",
  "sovrn.com",
  "spotx.tv",
  "spotxchange.com",
  "spoutable.com",
  "springserve.com",
  "stackadapt.com",
  "stickyadstv.com",
  "taboola.com",
  "teads.tv",
  "tidaltv.com",
  "trafficfactory.biz",
  "trafficjunky.com",
  "trafficjunky.net",
  "tremorhub.com",
  "tribalfusion.com",
  "triplelift.com",
  "tynt.com",
  "undertone.com",
  "unrulymedia.com",
  "vidoomy.com",
  "yieldlab.net",
  "yieldlove.com",
  "yieldmo.com",
  "yldbt.com",
  "zedo.com",
  "zemanta.com",
  "zergnet.com"
]);

// Slot-name prefixes (srcdoc/about:blank ads with no src domain) → network
// fallback. Checked with startsWith on iframe id/name and container id.
const TROVE_AD_SLOT_PREFIXES = {
  "google_ads_iframe": "google",
  "aswift_": "google",
  "div-gpt-ad": "google"
};

// Networks the inspector injects into (subset: creative-serving domains the
// click-through extractor understands). Kept here so detector and inspector
// derive from one module and cannot drift.
const TROVE_AD_INSPECT_DOMAINS = [
  "2mdn.net",
  "adform.net",
  "adnxs.com",
  "amazon-adsystem.com",
  "casalemedia.com",
  "criteo.com",
  "criteo.net",
  "doubleclick.net",
  "flashtalking.com",
  "googleadservices.com",
  "googlesyndication.com",
  "media.net",
  "mgid.com",
  "openx.net",
  "outbrain.com",
  "pubmatic.com",
  "revcontent.com",
  "rubiconproject.com",
  "smartadserver.com",
  "taboola.com",
  "teads.tv"
];

// chrome.scripting match patterns for the inspector registration.
const TROVE_AD_MATCH_PATTERNS = TROVE_AD_INSPECT_DOMAINS.flatMap((d) => [
  `https://${d}/*`,
  `https://*.${d}/*`,
]);

// Click-through query params that carry the landing URL, tried in order.
const TROVE_AD_CLICK_PARAMS = ["adurl","dest_url","destination","clickurl","click","clk","curl","redirect","redir","r","u","url"];

// The set entry (eTLD+1) a host falls under, or '' if not an ad host.
// Suffix walk instead of a public-suffix list: O(labels) Set lookups.
function troveAdDomainOf(host) {
  if (!host) return '';
  const parts = host.toLowerCase().split('.');
  for (let i = Math.max(0, parts.length - 4); i < parts.length - 1; i++) {
    const suffix = parts.slice(i).join('.');
    if (TROVE_AD_DOMAINS.has(suffix)) return suffix;
  }
  return '';
}
